// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlataformaGestaoIA.DataContext;

#nullable disable

namespace plataformagestaoiabe.Migrations
{
    [DbContext(typeof(PrincipalDataContext))]
    [Migration("20250206205327_CreateMigration")]
    partial class CreateMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PlataformaGestaoIA.Models.AllocationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("semester");

                    b.Property<int>("id_project")
                        .HasColumnType("int");

                    b.Property<int>("id_student")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_student");

                    b.HasIndex("id_project", "id_student", "Semester")
                        .IsUnique()
                        .HasDatabaseName("IX_AllocationResult_Unique");

                    b.ToTable("AllocationResult", (string)null);
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("cnpj");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.CompanyRepresentative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("cpf");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("internal_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("name");

                    b.Property<int?>("company_id")
                        .HasColumnType("int");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("company_id");

                    b.HasIndex("user_id");

                    b.HasIndex(new[] { "InternalCode" }, "IX_CompanyRepresentative_InternalCode")
                        .IsUnique();

                    b.ToTable("CompanyRepresentative", (string)null);
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.CourseSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Code" }, "IX_Code_Slug")
                        .IsUnique();

                    b.ToTable("CourseSubject", (string)null);
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.CurrentCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Campus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CurrentCourse");
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.GeneralConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConfigBody")
                        .IsRequired()
                        .HasColumnType("LONGTEXT")
                        .HasColumnName("config_body");

                    b.Property<string>("ConfigConsent")
                        .IsRequired()
                        .HasColumnType("LONGTEXT")
                        .HasColumnName("config_consent");

                    b.Property<string>("ConfigEmailDomainAvaliable")
                        .IsRequired()
                        .HasColumnType("LONGTEXT")
                        .HasColumnName("config_email_domain_avaliable");

                    b.Property<string>("ConfigHeader")
                        .IsRequired()
                        .HasColumnType("LONGTEXT")
                        .HasColumnName("config_header");

                    b.HasKey("Id");

                    b.ToTable("GeneralConfig", (string)null);
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("name");

                    b.Property<int?>("id_user")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_user")
                        .IsUnique();

                    b.ToTable("Professor", (string)null);
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("internal_code");

                    b.HasKey("Id");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.ProjectSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectSkill");
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ulong>("IsSoftSkill")
                        .HasColumnType("BIT")
                        .HasColumnName("is_soft_skill");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("name");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("tag");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Tag" }, "IX_Skill_Tag")
                        .IsUnique();

                    b.ToTable("Skill", (string)null);
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("cpf");

                    b.Property<string>("Cellphone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("cellphone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("name");

                    b.Property<string>("RA")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("ra");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("rg");

                    b.Property<int?>("id_current_course")
                        .HasColumnType("int");

                    b.Property<int?>("id_user")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_current_course")
                        .IsUnique();

                    b.HasIndex("id_user")
                        .IsUnique();

                    b.HasIndex(new[] { "RA" }, "IX_RA_Slug")
                        .IsUnique();

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.StudentRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<short>("ChoicePriority")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("choice_priority");

                    b.Property<short>("DoesNotMeetRequirements")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("does_not_meet_requirements");

                    b.Property<ulong>("EnrolledInIndustry4_0")
                        .HasColumnType("BIT")
                        .HasColumnName("enrolled_in_industry_4_0");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("file_path");

                    b.Property<DateTime>("FirstMeetingDate")
                        .HasColumnType("DATE")
                        .HasColumnName("first_meeting_date");

                    b.Property<ulong>("Presencial")
                        .HasColumnType("BIT")
                        .HasColumnName("presencial");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("DATE")
                        .HasColumnName("registration_date");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("VARCHAR(7)")
                        .HasColumnName("semester");

                    b.Property<string>("SkillsDescription")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("skills_description");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("StudentRegistrationScoreId")
                        .HasColumnType("int");

                    b.Property<short>("Subject")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("subject");

                    b.Property<int>("id_student")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentRegistrationScoreId");

                    b.HasIndex("id_student");

                    b.ToTable("StudentRegistration", (string)null);
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.StudentRegistrationScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AIProjectsScore")
                        .HasColumnType("INT")
                        .HasColumnName("ai_projects_score");

                    b.Property<int>("CertificationCoursesScore")
                        .HasColumnType("INT")
                        .HasColumnName("certification_courses_score");

                    b.Property<int>("HighGradeCoursesScore")
                        .HasColumnType("INT")
                        .HasColumnName("high_grade_courses_score");

                    b.Property<int>("HighGradeDisciplineScore")
                        .HasColumnType("INT")
                        .HasColumnName("high_grade_discipline_score");

                    b.Property<int>("InstitutionalMonitoringProgramScore")
                        .HasColumnType("INT")
                        .HasColumnName("institutional_monitoring_program_score");

                    b.Property<int>("InternshipEmploymentScore")
                        .HasColumnType("INT")
                        .HasColumnName("internship_employment_score");

                    b.Property<int>("JuniorEnterpriseExperienceScore")
                        .HasColumnType("INT")
                        .HasColumnName("junior_enterprise_experience_score");

                    b.Property<int>("LowLevelTechScore")
                        .HasColumnType("INT")
                        .HasColumnName("low_level_tech_score");

                    b.Property<float>("PerformanceCoefficient")
                        .HasColumnType("FLOAT")
                        .HasColumnName("performance_coefficient");

                    b.Property<int>("ProjectInTechnologicalHotelScore")
                        .HasColumnType("INT")
                        .HasColumnName("project_in_technological_hotel_score");

                    b.Property<int>("ScientificInitiationProgramScore")
                        .HasColumnType("INT")
                        .HasColumnName("scientific_initiation_program_score");

                    b.Property<string>("ScoreCoursesDescription")
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("score_courses_description");

                    b.Property<int>("TechnologyCertificationScore")
                        .HasColumnType("INT")
                        .HasColumnName("technology_certification_score");

                    b.Property<int>("VolunteeringScore")
                        .HasColumnType("INT")
                        .HasColumnName("volunteering_score");

                    b.HasKey("Id");

                    b.ToTable("StudentRegistrationScores", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "studentRegistrationScore");
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.StudentRegistrationSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<short>("Level")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("level");

                    b.Property<int>("id_skill")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_skill");

                    b.ToTable("StudentRegistrationSkill", (string)null);
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("email");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("password_hash");

                    b.Property<string>("Slug")
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Slug" }, "IX_User_Slug")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Project_ProjectSkill", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectSkillId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "ProjectSkillId");

                    b.HasIndex("ProjectSkillId");

                    b.ToTable("Project_ProjectSkill");
                });

            modelBuilder.Entity("StudentRegistration_RegistrationSkill", b =>
                {
                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationSkillId")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .HasColumnType("VARCHAR(7)")
                        .HasColumnName("semester");

                    b.HasKey("RegistrationId", "RegistrationSkillId");

                    b.HasIndex("RegistrationSkillId");

                    b.ToTable("StudentRegistration_RegistrationSkill");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("id_role")
                        .HasColumnType("int");

                    b.Property<int>("id_user")
                        .HasColumnType("int");

                    b.HasKey("id_role", "id_user");

                    b.HasIndex("id_user");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("User_Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("User_Project");
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.AllocationResult", b =>
                {
                    b.HasOne("PlataformaGestaoIA.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("id_project")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AllocationResult_Project");

                    b.HasOne("PlataformaGestaoIA.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("id_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AllocationResult_Student");

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.CompanyRepresentative", b =>
                {
                    b.HasOne("PlataformaGestaoIA.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_CompanyRepresentative_Company");

                    b.HasOne("PlataformaGestaoIA.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_CompanyRepresentative_User");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.Professor", b =>
                {
                    b.HasOne("PlataformaGestaoIA.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("PlataformaGestaoIA.Models.Professor", "id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Professor_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.ProjectSkill", b =>
                {
                    b.HasOne("PlataformaGestaoIA.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.Student", b =>
                {
                    b.HasOne("PlataformaGestaoIA.Models.CurrentCourse", "CurrentCourse")
                        .WithOne()
                        .HasForeignKey("PlataformaGestaoIA.Models.Student", "id_current_course")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Student_CurrentCourse");

                    b.HasOne("PlataformaGestaoIA.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("PlataformaGestaoIA.Models.Student", "id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Student_User");

                    b.Navigation("CurrentCourse");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.StudentRegistration", b =>
                {
                    b.HasOne("PlataformaGestaoIA.Models.Student", null)
                        .WithMany("StudentRegistrations")
                        .HasForeignKey("StudentId");

                    b.HasOne("PlataformaGestaoIA.Models.StudentRegistrationScore", "StudentRegistrationScore")
                        .WithMany()
                        .HasForeignKey("StudentRegistrationScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaGestaoIA.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("id_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StudentReg_Student");

                    b.Navigation("Student");

                    b.Navigation("StudentRegistrationScore");
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.StudentRegistrationSkill", b =>
                {
                    b.HasOne("PlataformaGestaoIA.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("id_skill")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StudentRegSkill_Skill");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Project_ProjectSkill", b =>
                {
                    b.HasOne("PlataformaGestaoIA.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectReg_ProjectSkill_ProjectId");

                    b.HasOne("PlataformaGestaoIA.Models.ProjectSkill", null)
                        .WithMany()
                        .HasForeignKey("ProjectSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Project_ProjectSkill_SkillId");
                });

            modelBuilder.Entity("StudentRegistration_RegistrationSkill", b =>
                {
                    b.HasOne("PlataformaGestaoIA.Models.StudentRegistration", null)
                        .WithMany()
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StdReg_RegSkill_RegId");

                    b.HasOne("PlataformaGestaoIA.Models.StudentRegistrationSkill", null)
                        .WithMany()
                        .HasForeignKey("RegistrationSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StdReg_RegSkill_SkillId");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("PlataformaGestaoIA.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("id_role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_RoleId");

                    b.HasOne("PlataformaGestaoIA.Models.User", null)
                        .WithMany()
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_UserId");
                });

            modelBuilder.Entity("User_Project", b =>
                {
                    b.HasOne("PlataformaGestaoIA.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_ProjectId");

                    b.HasOne("PlataformaGestaoIA.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Project_UserId");
                });

            modelBuilder.Entity("PlataformaGestaoIA.Models.Student", b =>
                {
                    b.Navigation("StudentRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
